version: "3.8"

services:
  app:
    image: achilif17/medicine-service:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 7203312
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 7203312
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"

  nginx:
    image: public.ecr.aws/nginx/nginx:stable-alpine3.19-slim
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=app
      - NGINX_PORT=8080
    depends_on:
      - app


